module.exports = [
  { pattern: /absolute/ },
  { pattern: /^(p-[^/]+|pl-[^/]+)$/ },
  { pattern: /^font-[^/]+$/ },
  { pattern: /^rounded-[^/]+$/ },
  { pattern: /^leading-[^/]+$/ },
  { pattern: /^(w-[^/]+|h-[^/]+)$/ },
  { pattern: /^text-[^/]+$/ },
  { pattern: /^border-[^/]+$/ },
  { pattern: /^bg-[^/]+$/ },
  { pattern: /^from-[^/]+$/ },
  { pattern: /^via-[^/]+$/ },
  { pattern: /^to-[^/]+$/ },
  { pattern: /^bg-opacity-[^/]+$/ },
  { pattern: /^scale-[^/]+$/ },
  { pattern: /^transform-[^/]+$/ },
  { pattern: /^-translate-[^/]+$/ },
  { pattern: /^translate-[^/]+$/ },
  { pattern: /^object-[^/]+$/ },
  { pattern: /^z-[^/]+$/ },
  { pattern: /^opacity-[^/]+$/ },
  { pattern: /^(mr-[^/]+|ml-[^/]+)$/ },
  { pattern: /^(space-x-[^/]+|space-y-[^/]+)$/ },
  { pattern: /line-clamp-[0-9]+$/ },
  { pattern: /grid-cols-[0-9]+$/ },
];
