import { NextApiRequest, NextApiResponse } from "next";
import requestHandler from "@/pages/_requestHandler";
import AI from "@/services/AI";

import { exampleSchema } from "@/services/AI/schemas";

import { IChatCall } from "@/services/AI/types";

const handler = requestHandler().get(
  async (req: NextApiRequest, res: NextApiResponse) => {
    try {
      const data = [
        {
          type: "Feature",
          properties: {
            countryCode: "CHL",
            countryName: "Chile",
            elevation: "89.4",
            organizationId: "78994063",
            organizationName: "Colegio Madres Dominicas",
            protocol: "water_temperatures",
            siteId: "324983",
            siteName: "Río Toltén Casa de Martín",
            watertemperaturesComments: "null",
            watertemperaturesMeasuredAt: "2024-05-16T20:18:00",
            watertemperaturesTemperatureMethod: "probe",
            watertemperaturesThermometerProbeMfg: "null",
            watertemperaturesThermometerProbeModel: "null",
            watertemperaturesUserid: "78994049",
            watertemperaturesWaterBodyState: "normal",
            watertemperaturesWaterTempC: "13",
          },
          geometry: {
            type: "Point",
            coordinates: [-72.61659, -38.98968],
          },
        },
        {
          type: "Feature",
          properties: {
            countryCode: "CHL",
            countryName: "Chile",
            elevation: "86.0",
            organizationId: "78994063",
            organizationName: "Colegio Madres Dominicas",
            protocol: "water_temperatures",
            siteId: "324985",
            siteName: "Rocas chicas las Garzas",
            watertemperaturesComments: "null",
            watertemperaturesMeasuredAt: "2024-05-16T20:15:00",
            watertemperaturesTemperatureMethod: "probe",
            watertemperaturesThermometerProbeMfg: "null",
            watertemperaturesThermometerProbeModel: "null",
            watertemperaturesUserid: "78994049",
            watertemperaturesWaterBodyState: "normal",
            watertemperaturesWaterTempC: "12.2",
          },
          geometry: {
            type: "Point",
            coordinates: [-72.62252, -38.98579],
          },
        },
        {
          type: "Feature",
          properties: {
            countryCode: "CHL",
            countryName: "Chile",
            elevation: "86.0",
            organizationId: "78994063",
            organizationName: "Colegio Madres Dominicas",
            protocol: "water_temperatures",
            siteId: "324985",
            siteName: "Rocas chicas las Garzas",
            watertemperaturesComments: "null",
            watertemperaturesMeasuredAt: "2023-10-19T20:54:00",
            watertemperaturesTemperatureMethod: "probe",
            watertemperaturesThermometerProbeMfg: "null",
            watertemperaturesThermometerProbeModel: "null",
            watertemperaturesUserid: "78994049",
            watertemperaturesWaterBodyState: "normal",
            watertemperaturesWaterTempC: "16",
          },
          geometry: {
            type: "Point",
            coordinates: [-72.62252, -38.98579],
          },
        },
        {
          type: "Feature",
          properties: {
            countryCode: "CHL",
            countryName: "Chile",
            elevation: "89.4",
            organizationId: "78994063",
            organizationName: "Colegio Madres Dominicas",
            protocol: "water_temperatures",
            siteId: "324983",
            siteName: "Río Toltén Casa de Martín",
            watertemperaturesComments: "null",
            watertemperaturesMeasuredAt: "2023-10-19T20:42:00",
            watertemperaturesTemperatureMethod: "probe",
            watertemperaturesThermometerProbeMfg: "null",
            watertemperaturesThermometerProbeModel: "null",
            watertemperaturesUserid: "78994049",
            watertemperaturesWaterBodyState: "normal",
            watertemperaturesWaterTempC: "17.2",
          },
          geometry: {
            type: "Point",
            coordinates: [-72.61659, -38.98968],
          },
        },
        {
          type: "Feature",
          properties: {
            countryCode: "CHL",
            countryName: "Chile",
            elevation: "86.0",
            organizationId: "78994063",
            organizationName: "Colegio Madres Dominicas",
            protocol: "water_temperatures",
            siteId: "324985",
            siteName: "Rocas chicas las Garzas",
            watertemperaturesComments: "null",
            watertemperaturesMeasuredAt: "2023-10-19T20:57:00",
            watertemperaturesTemperatureMethod: "probe",
            watertemperaturesThermometerProbeMfg: "null",
            watertemperaturesThermometerProbeModel: "null",
            watertemperaturesUserid: "78994049",
            watertemperaturesWaterBodyState: "normal",
            watertemperaturesWaterTempC: "16",
          },
          geometry: {
            type: "Point",
            coordinates: [-72.62252, -38.98579],
          },
        },
        {
          type: "Feature",
          properties: {
            countryCode: "CHL",
            countryName: "Chile",
            elevation: "89.4",
            organizationId: "78994063",
            organizationName: "Colegio Madres Dominicas",
            protocol: "water_temperatures",
            siteId: "324983",
            siteName: "Río Toltén Casa de Martín",
            watertemperaturesComments: "null",
            watertemperaturesMeasuredAt: "2023-10-19T20:45:00",
            watertemperaturesTemperatureMethod: "probe",
            watertemperaturesThermometerProbeMfg: "null",
            watertemperaturesThermometerProbeModel: "null",
            watertemperaturesUserid: "78994049",
            watertemperaturesWaterBodyState: "normal",
            watertemperaturesWaterTempC: "17.2",
          },
          geometry: {
            type: "Point",
            coordinates: [-72.61659, -38.98968],
          },
        },
        {
          type: "Feature",
          properties: {
            countryCode: "CHL",
            countryName: "Chile",
            elevation: "88.8",
            organizationId: "78994063",
            organizationName: "Colegio Madres Dominicas",
            protocol: "water_temperatures",
            siteId: "324984",
            siteName: "Las rocas grandes Río Toltén",
            watertemperaturesComments: "null",
            watertemperaturesMeasuredAt: "2023-10-19T20:49:00",
            watertemperaturesTemperatureMethod: "probe",
            watertemperaturesThermometerProbeMfg: "null",
            watertemperaturesThermometerProbeModel: "null",
            watertemperaturesUserid: "78994049",
            watertemperaturesWaterBodyState: "normal",
            watertemperaturesWaterTempC: "16.9",
          },
          geometry: {
            type: "Point",
            coordinates: [-72.61956, -38.98617],
          },
        },
        {
          type: "Feature",
          properties: {
            countryCode: "CHL",
            countryName: "Chile",
            elevation: "86.0",
            organizationId: "78994063",
            organizationName: "Colegio Madres Dominicas",
            protocol: "water_temperatures",
            siteId: "324985",
            siteName: "Rocas chicas las Garzas",
            watertemperaturesComments: "null",
            watertemperaturesMeasuredAt: "2023-10-19T20:38:00",
            watertemperaturesTemperatureMethod: "probe",
            watertemperaturesThermometerProbeMfg: "null",
            watertemperaturesThermometerProbeModel: "null",
            watertemperaturesUserid: "78994049",
            watertemperaturesWaterBodyState: "normal",
            watertemperaturesWaterTempC: "17.2",
          },
          geometry: {
            type: "Point",
            coordinates: [-72.62252, -38.98579],
          },
        },
        {
          type: "Feature",
          properties: {
            countryCode: "CHL",
            countryName: "Chile",
            elevation: "88.8",
            organizationId: "78994063",
            organizationName: "Colegio Madres Dominicas",
            protocol: "water_temperatures",
            siteId: "324984",
            siteName: "Las rocas grandes Río Toltén",
            watertemperaturesComments: "null",
            watertemperaturesMeasuredAt: "2023-10-19T20:47:00",
            watertemperaturesTemperatureMethod: "probe",
            watertemperaturesThermometerProbeMfg: "null",
            watertemperaturesThermometerProbeModel: "null",
            watertemperaturesUserid: "78994049",
            watertemperaturesWaterBodyState: "normal",
            watertemperaturesWaterTempC: "16.9",
          },
          geometry: {
            type: "Point",
            coordinates: [-72.61956, -38.98617],
          },
        },
        {
          type: "Feature",
          properties: {
            countryCode: "CHL",
            countryName: "Chile",
            elevation: "88.8",
            organizationId: "78994063",
            organizationName: "Colegio Madres Dominicas",
            protocol: "water_temperatures",
            siteId: "324984",
            siteName: "Las rocas grandes Río Toltén",
            watertemperaturesComments: "null",
            watertemperaturesMeasuredAt: "2023-10-19T20:53:00",
            watertemperaturesTemperatureMethod: "probe",
            watertemperaturesThermometerProbeMfg: "null",
            watertemperaturesThermometerProbeModel: "null",
            watertemperaturesUserid: "78994049",
            watertemperaturesWaterBodyState: "normal",
            watertemperaturesWaterTempC: "16.9",
          },
          geometry: {
            type: "Point",
            coordinates: [-72.61956, -38.98617],
          },
        },
        {
          type: "Feature",
          properties: {
            countryCode: "CHL",
            countryName: "Chile",
            elevation: "86.0",
            organizationId: "78994063",
            organizationName: "Colegio Madres Dominicas",
            protocol: "water_temperatures",
            siteId: "324985",
            siteName: "Rocas chicas las Garzas",
            watertemperaturesComments: "null",
            watertemperaturesMeasuredAt: "2023-08-03T21:15:00",
            watertemperaturesTemperatureMethod: "probe",
            watertemperaturesThermometerProbeMfg: "null",
            watertemperaturesThermometerProbeModel: "null",
            watertemperaturesUserid: "87166017",
            watertemperaturesWaterBodyState: "normal",
            watertemperaturesWaterTempC: "12.1",
          },
          geometry: {
            type: "Point",
            coordinates: [-72.62252, -38.98579],
          },
        },
        {
          type: "Feature",
          properties: {
            countryCode: "CHL",
            countryName: "Chile",
            elevation: "88.8",
            organizationId: "78994063",
            organizationName: "Colegio Madres Dominicas",
            protocol: "water_temperatures",
            siteId: "324984",
            siteName: "Las rocas grandes Río Toltén",
            watertemperaturesComments: "null",
            watertemperaturesMeasuredAt: "2023-08-03T21:00:00",
            watertemperaturesTemperatureMethod: "probe",
            watertemperaturesThermometerProbeMfg: "null",
            watertemperaturesThermometerProbeModel: "null",
            watertemperaturesUserid: "87166017",
            watertemperaturesWaterBodyState: "normal",
            watertemperaturesWaterTempC: "10.9",
          },
          geometry: {
            type: "Point",
            coordinates: [-72.61956, -38.98617],
          },
        },
        {
          type: "Feature",
          properties: {
            countryCode: "CHL",
            countryName: "Chile",
            elevation: "251.4",
            organizationId: "286213",
            organizationName: "La Tuna",
            protocol: "water_temperatures",
            siteId: "1475",
            siteName: "Valdivia y los Robles:SWS-01",
            watertemperaturesComments: "null",
            watertemperaturesMeasuredAt: "2010-12-31T17:10:00",
            watertemperaturesTemperatureMethod: "alcohol-filled thermometer",
            watertemperaturesThermometerProbeMfg: "Arquimed",
            watertemperaturesThermometerProbeModel: "alcohol termomet",
            watertemperaturesUserid: "-1",
            watertemperaturesWaterBodyState: "normal",
            watertemperaturesWaterTempC: "18",
          },
          geometry: {
            type: "Point",
            coordinates: [-71.06, -34.63],
          },
        },
        {
          type: "Feature",
          properties: {
            countryCode: "CHL",
            countryName: "Chile",
            elevation: "251.4",
            organizationId: "286213",
            organizationName: "La Tuna",
            protocol: "water_temperatures",
            siteId: "1475",
            siteName: "Valdivia y los Robles:SWS-01",
            watertemperaturesComments: "null",
            watertemperaturesMeasuredAt: "2010-12-10T16:45:00",
            watertemperaturesTemperatureMethod: "alcohol-filled thermometer",
            watertemperaturesThermometerProbeMfg: "Arquimed",
            watertemperaturesThermometerProbeModel: "alcohol termomet",
            watertemperaturesUserid: "-1",
            watertemperaturesWaterBodyState: "normal",
            watertemperaturesWaterTempC: "18",
          },
          geometry: {
            type: "Point",
            coordinates: [-71.06, -34.63],
          },
        },
        {
          type: "Feature",
          properties: {
            countryCode: "CHL",
            countryName: "Chile",
            elevation: "251.4",
            organizationId: "286213",
            organizationName: "La Tuna",
            protocol: "water_temperatures",
            siteId: "1475",
            siteName: "Valdivia y los Robles:SWS-01",
            watertemperaturesComments: "null",
            watertemperaturesMeasuredAt: "2010-12-03T17:00:00",
            watertemperaturesTemperatureMethod: "alcohol-filled thermometer",
            watertemperaturesThermometerProbeMfg: "Arquimed",
            watertemperaturesThermometerProbeModel: "alcohol termomet",
            watertemperaturesUserid: "-1",
            watertemperaturesWaterBodyState: "normal",
            watertemperaturesWaterTempC: "20",
          },
          geometry: {
            type: "Point",
            coordinates: [-71.06, -34.63],
          },
        },
        {
          type: "Feature",
          properties: {
            countryCode: "CHL",
            countryName: "Chile",
            elevation: "251.4",
            organizationId: "286213",
            organizationName: "La Tuna",
            protocol: "water_temperatures",
            siteId: "1475",
            siteName: "Valdivia y los Robles:SWS-01",
            watertemperaturesComments: "null",
            watertemperaturesMeasuredAt: "2010-11-19T17:10:00",
            watertemperaturesTemperatureMethod: "alcohol-filled thermometer",
            watertemperaturesThermometerProbeMfg: "Arquimed",
            watertemperaturesThermometerProbeModel: "alcohol termomet",
            watertemperaturesUserid: "-1",
            watertemperaturesWaterBodyState: "normal",
            watertemperaturesWaterTempC: "21",
          },
          geometry: {
            type: "Point",
            coordinates: [-71.06, -34.63],
          },
        },
        {
          type: "Feature",
          properties: {
            countryCode: "CHL",
            countryName: "Chile",
            elevation: "251.4",
            organizationId: "286213",
            organizationName: "La Tuna",
            protocol: "water_temperatures",
            siteId: "1475",
            siteName: "Valdivia y los Robles:SWS-01",
            watertemperaturesComments: "null",
            watertemperaturesMeasuredAt: "2010-11-05T17:00:00",
            watertemperaturesTemperatureMethod: "alcohol-filled thermometer",
            watertemperaturesThermometerProbeMfg: "Arquimed",
            watertemperaturesThermometerProbeModel: "alcohol termomet",
            watertemperaturesUserid: "-1",
            watertemperaturesWaterBodyState: "normal",
            watertemperaturesWaterTempC: "24",
          },
          geometry: {
            type: "Point",
            coordinates: [-71.06, -34.63],
          },
        },
        {
          type: "Feature",
          properties: {
            countryCode: "CHL",
            countryName: "Chile",
            elevation: "251.4",
            organizationId: "286213",
            organizationName: "La Tuna",
            protocol: "water_temperatures",
            siteId: "1475",
            siteName: "Valdivia y los Robles:SWS-01",
            watertemperaturesComments: "null",
            watertemperaturesMeasuredAt: "2010-10-22T17:10:00",
            watertemperaturesTemperatureMethod: "alcohol-filled thermometer",
            watertemperaturesThermometerProbeMfg: "Arquimed",
            watertemperaturesThermometerProbeModel: "alcohol termomet",
            watertemperaturesUserid: "-1",
            watertemperaturesWaterBodyState: "normal",
            watertemperaturesWaterTempC: "16",
          },
          geometry: {
            type: "Point",
            coordinates: [-71.06, -34.63],
          },
        },
        {
          type: "Feature",
          properties: {
            countryCode: "CHL",
            countryName: "Chile",
            elevation: "251.4",
            organizationId: "286213",
            organizationName: "La Tuna",
            protocol: "water_temperatures",
            siteId: "1475",
            siteName: "Valdivia y los Robles:SWS-01",
            watertemperaturesComments: "null",
            watertemperaturesMeasuredAt: "2010-10-14T17:00:00",
            watertemperaturesTemperatureMethod: "alcohol-filled thermometer",
            watertemperaturesThermometerProbeMfg: "Arquimed",
            watertemperaturesThermometerProbeModel: "alcohol termomet",
            watertemperaturesUserid: "-1",
            watertemperaturesWaterBodyState: "normal",
            watertemperaturesWaterTempC: "12",
          },
          geometry: {
            type: "Point",
            coordinates: [-71.06, -34.63],
          },
        },
        {
          type: "Feature",
          properties: {
            countryCode: "CHL",
            countryName: "Chile",
            elevation: "251.4",
            organizationId: "286213",
            organizationName: "La Tuna",
            protocol: "water_temperatures",
            siteId: "1475",
            siteName: "Valdivia y los Robles:SWS-01",
            watertemperaturesComments: "null",
            watertemperaturesMeasuredAt: "2010-10-08T17:00:00",
            watertemperaturesTemperatureMethod: "alcohol-filled thermometer",
            watertemperaturesThermometerProbeMfg: "Arquimed",
            watertemperaturesThermometerProbeModel: "alcohol termomet",
            watertemperaturesUserid: "-1",
            watertemperaturesWaterBodyState: "normal",
            watertemperaturesWaterTempC: "17",
          },
          geometry: {
            type: "Point",
            coordinates: [-71.06, -34.63],
          },
        },
        {
          type: "Feature",
          properties: {
            countryCode: "CHL",
            countryName: "Chile",
            elevation: "251.4",
            organizationId: "286213",
            organizationName: "La Tuna",
            protocol: "water_temperatures",
            siteId: "1475",
            siteName: "Valdivia y los Robles:SWS-01",
            watertemperaturesComments: "null",
            watertemperaturesMeasuredAt: "2010-09-24T17:00:00",
            watertemperaturesTemperatureMethod: "alcohol-filled thermometer",
            watertemperaturesThermometerProbeMfg: "Arquimed",
            watertemperaturesThermometerProbeModel: "alcohol termomet",
            watertemperaturesUserid: "-1",
            watertemperaturesWaterBodyState: "normal",
            watertemperaturesWaterTempC: "19",
          },
          geometry: {
            type: "Point",
            coordinates: [-71.06, -34.63],
          },
        },
        {
          type: "Feature",
          properties: {
            countryCode: "CHL",
            countryName: "Chile",
            elevation: "224.0",
            organizationId: "124407",
            organizationName: "Escuela Rural de Niebla",
            protocol: "water_temperatures",
            siteId: "1495",
            siteName: "ESTERO LA HUAIRONA:SWS-02",
            watertemperaturesComments: "hello",
            watertemperaturesMeasuredAt: "2008-05-28T16:11:00",
            watertemperaturesTemperatureMethod: "alcohol-filled thermometer",
            watertemperaturesThermometerProbeMfg: "null",
            watertemperaturesThermometerProbeModel: "null",
            watertemperaturesUserid: "-1",
            watertemperaturesWaterBodyState: "normal",
            watertemperaturesWaterTempC: "10.2",
          },
          geometry: {
            type: "Point",
            coordinates: [-71.6, -33.95],
          },
        },
        {
          type: "Feature",
          properties: {
            countryCode: "CHL",
            countryName: "Chile",
            elevation: "16.0",
            organizationId: "124407",
            organizationName: "Escuela Rural de Niebla",
            protocol: "water_temperatures",
            siteId: "1494",
            siteName: "MUELLE NIEBLA:SWS-01",
            watertemperaturesComments: "null",
            watertemperaturesMeasuredAt: "2007-11-28T21:21:00",
            watertemperaturesTemperatureMethod: "alcohol-filled thermometer",
            watertemperaturesThermometerProbeMfg: "null",
            watertemperaturesThermometerProbeModel: "null",
            watertemperaturesUserid: "-1",
            watertemperaturesWaterBodyState: "normal",
            watertemperaturesWaterTempC: "14.5",
          },
          geometry: {
            type: "Point",
            coordinates: [-71.6, -33.95],
          },
        },
        {
          type: "Feature",
          properties: {
            countryCode: "CHL",
            countryName: "Chile",
            elevation: "224.0",
            organizationId: "124407",
            organizationName: "Escuela Rural de Niebla",
            protocol: "water_temperatures",
            siteId: "1495",
            siteName: "ESTERO LA HUAIRONA:SWS-02",
            watertemperaturesComments:
              "en la hora de medicion se produce la descarga de aguas dservidas de la planta de tratamiento que queda a 200 metros del lugar de medicion. Estas aguas servidas son tratadas solo en primer grado.",
            watertemperaturesMeasuredAt: "2007-11-15T16:30:00",
            watertemperaturesTemperatureMethod: "alcohol-filled thermometer",
            watertemperaturesThermometerProbeMfg: "null",
            watertemperaturesThermometerProbeModel: "null",
            watertemperaturesUserid: "-1",
            watertemperaturesWaterBodyState: "normal",
            watertemperaturesWaterTempC: "12",
          },
          geometry: {
            type: "Point",
            coordinates: [-71.6, -33.95],
          },
        },
        {
          type: "Feature",
          properties: {
            countryCode: "CHL",
            countryName: "Chile",
            elevation: "224.0",
            organizationId: "124407",
            organizationName: "Escuela Rural de Niebla",
            protocol: "water_temperatures",
            siteId: "1495",
            siteName: "ESTERO LA HUAIRONA:SWS-02",
            watertemperaturesComments: "null",
            watertemperaturesMeasuredAt: "2007-10-11T21:45:00",
            watertemperaturesTemperatureMethod: "alcohol-filled thermometer",
            watertemperaturesThermometerProbeMfg: "null",
            watertemperaturesThermometerProbeModel: "null",
            watertemperaturesUserid: "-1",
            watertemperaturesWaterBodyState: "normal",
            watertemperaturesWaterTempC: "11.8",
          },
          geometry: {
            type: "Point",
            coordinates: [-71.6, -33.95],
          },
        },
        {
          type: "Feature",
          properties: {
            countryCode: "CHL",
            countryName: "Chile",
            elevation: "224.0",
            organizationId: "124407",
            organizationName: "Escuela Rural de Niebla",
            protocol: "water_temperatures",
            siteId: "1495",
            siteName: "ESTERO LA HUAIRONA:SWS-02",
            watertemperaturesComments: "null",
            watertemperaturesMeasuredAt: "2007-04-05T21:50:00",
            watertemperaturesTemperatureMethod: "alcohol-filled thermometer",
            watertemperaturesThermometerProbeMfg: "null",
            watertemperaturesThermometerProbeModel: "null",
            watertemperaturesUserid: "-1",
            watertemperaturesWaterBodyState: "normal",
            watertemperaturesWaterTempC: "13.2",
          },
          geometry: {
            type: "Point",
            coordinates: [-71.6, -33.95],
          },
        },
        {
          type: "Feature",
          properties: {
            countryCode: "CHL",
            countryName: "Chile",
            elevation: "224.0",
            organizationId: "124407",
            organizationName: "Escuela Rural de Niebla",
            protocol: "water_temperatures",
            siteId: "1495",
            siteName: "ESTERO LA HUAIRONA:SWS-02",
            watertemperaturesComments: "null",
            watertemperaturesMeasuredAt: "2006-12-07T21:50:00",
            watertemperaturesTemperatureMethod: "alcohol-filled thermometer",
            watertemperaturesThermometerProbeMfg: "null",
            watertemperaturesThermometerProbeModel: "null",
            watertemperaturesUserid: "-1",
            watertemperaturesWaterBodyState: "normal",
            watertemperaturesWaterTempC: "13.3",
          },
          geometry: {
            type: "Point",
            coordinates: [-71.6, -33.95],
          },
        },
        {
          type: "Feature",
          properties: {
            countryCode: "CHL",
            countryName: "Chile",
            elevation: "224.0",
            organizationId: "124407",
            organizationName: "Escuela Rural de Niebla",
            protocol: "water_temperatures",
            siteId: "1495",
            siteName: "ESTERO LA HUAIRONA:SWS-02",
            watertemperaturesComments:
              "Al estero desagua una planta de tratamiento de aguas servidas, desde el a?o 2004.-",
            watertemperaturesMeasuredAt: "2006-07-14T17:48:00",
            watertemperaturesTemperatureMethod: "alcohol-filled thermometer",
            watertemperaturesThermometerProbeMfg: "null",
            watertemperaturesThermometerProbeModel: "null",
            watertemperaturesUserid: "-1",
            watertemperaturesWaterBodyState: "normal",
            watertemperaturesWaterTempC: "8.5",
          },
          geometry: {
            type: "Point",
            coordinates: [-71.6, -33.95],
          },
        },
        {
          type: "Feature",
          properties: {
            countryCode: "CHL",
            countryName: "Chile",
            elevation: "16.0",
            organizationId: "124407",
            organizationName: "Escuela Rural de Niebla",
            protocol: "water_temperatures",
            siteId: "1494",
            siteName: "MUELLE NIEBLA:SWS-01",
            watertemperaturesComments:
              "Habia viento fuerte y oleaje a la hora de la medicion.",
            watertemperaturesMeasuredAt: "2006-07-14T17:48:00",
            watertemperaturesTemperatureMethod: "alcohol-filled thermometer",
            watertemperaturesThermometerProbeMfg: "null",
            watertemperaturesThermometerProbeModel: "null",
            watertemperaturesUserid: "-1",
            watertemperaturesWaterBodyState: "normal",
            watertemperaturesWaterTempC: "9",
          },
          geometry: {
            type: "Point",
            coordinates: [-71.6, -33.95],
          },
        },
        {
          type: "Feature",
          properties: {
            countryCode: "CHL",
            countryName: "Chile",
            elevation: "16.0",
            organizationId: "124407",
            organizationName: "Escuela Rural de Niebla",
            protocol: "water_temperatures",
            siteId: "1494",
            siteName: "MUELLE NIEBLA:SWS-01",
            watertemperaturesComments: "null",
            watertemperaturesMeasuredAt: "2006-06-08T12:40:00",
            watertemperaturesTemperatureMethod: "probe",
            watertemperaturesThermometerProbeMfg: "null",
            watertemperaturesThermometerProbeModel: "null",
            watertemperaturesUserid: "-1",
            watertemperaturesWaterBodyState: "normal",
            watertemperaturesWaterTempC: "11",
          },
          geometry: {
            type: "Point",
            coordinates: [-71.6, -33.95],
          },
        },
        {
          type: "Feature",
          properties: {
            countryCode: "CHL",
            countryName: "Chile",
            elevation: "224.0",
            organizationId: "124407",
            organizationName: "Escuela Rural de Niebla",
            protocol: "water_temperatures",
            siteId: "1495",
            siteName: "ESTERO LA HUAIRONA:SWS-02",
            watertemperaturesComments: "null",
            watertemperaturesMeasuredAt: "2006-06-08T11:30:00",
            watertemperaturesTemperatureMethod: "alcohol-filled thermometer",
            watertemperaturesThermometerProbeMfg: "null",
            watertemperaturesThermometerProbeModel: "null",
            watertemperaturesUserid: "-1",
            watertemperaturesWaterBodyState: "normal",
            watertemperaturesWaterTempC: "10",
          },
          geometry: {
            type: "Point",
            coordinates: [-71.6, -33.95],
          },
        },
        {
          type: "Feature",
          properties: {
            countryCode: "CHL",
            countryName: "Chile",
            elevation: "16.0",
            organizationId: "124407",
            organizationName: "Escuela Rural de Niebla",
            protocol: "water_temperatures",
            siteId: "1494",
            siteName: "MUELLE NIEBLA:SWS-01",
            watertemperaturesComments: "null",
            watertemperaturesMeasuredAt: "2005-11-24T10:30:00",
            watertemperaturesTemperatureMethod: "null",
            watertemperaturesThermometerProbeMfg: "null",
            watertemperaturesThermometerProbeModel: "null",
            watertemperaturesUserid: "-1",
            watertemperaturesWaterBodyState: "normal",
            watertemperaturesWaterTempC: "13",
          },
          geometry: {
            type: "Point",
            coordinates: [-71.6, -33.95],
          },
        },
        {
          type: "Feature",
          properties: {
            countryCode: "CHL",
            countryName: "Chile",
            elevation: "16.0",
            organizationId: "124407",
            organizationName: "Escuela Rural de Niebla",
            protocol: "water_temperatures",
            siteId: "1494",
            siteName: "MUELLE NIEBLA:SWS-01",
            watertemperaturesComments: "null",
            watertemperaturesMeasuredAt: "2005-11-10T11:15:00",
            watertemperaturesTemperatureMethod: "null",
            watertemperaturesThermometerProbeMfg: "null",
            watertemperaturesThermometerProbeModel: "null",
            watertemperaturesUserid: "-1",
            watertemperaturesWaterBodyState: "flooded",
            watertemperaturesWaterTempC: "13.7",
          },
          geometry: {
            type: "Point",
            coordinates: [-71.6, -33.95],
          },
        },
        {
          type: "Feature",
          properties: {
            countryCode: "CHL",
            countryName: "Chile",
            elevation: "224.0",
            organizationId: "124407",
            organizationName: "Escuela Rural de Niebla",
            protocol: "water_temperatures",
            siteId: "1495",
            siteName: "ESTERO LA HUAIRONA:SWS-02",
            watertemperaturesComments: "null",
            watertemperaturesMeasuredAt: "2005-11-03T17:00:00",
            watertemperaturesTemperatureMethod: "null",
            watertemperaturesThermometerProbeMfg: "null",
            watertemperaturesThermometerProbeModel: "null",
            watertemperaturesUserid: "-1",
            watertemperaturesWaterBodyState: "normal",
            watertemperaturesWaterTempC: "12",
          },
          geometry: {
            type: "Point",
            coordinates: [-71.6, -33.95],
          },
        },
        {
          type: "Feature",
          properties: {
            countryCode: "CHL",
            countryName: "Chile",
            elevation: "1067.2",
            organizationId: "129720",
            organizationName: "Centro Educacional Valle Hermoso",
            protocol: "water_temperatures",
            siteId: "1487",
            siteName: "QUEBRADA DE MACUL  2:SWS-02",
            watertemperaturesComments:
              "no se pudo medir el PH del agua porque no teniamos el peachimetro, ya que el alumno encargado no se presento.",
            watertemperaturesMeasuredAt: "2005-10-22T13:05:00",
            watertemperaturesTemperatureMethod: "null",
            watertemperaturesThermometerProbeMfg: "null",
            watertemperaturesThermometerProbeModel: "null",
            watertemperaturesUserid: "-1",
            watertemperaturesWaterBodyState: "normal",
            watertemperaturesWaterTempC: "10.4",
          },
          geometry: {
            type: "Point",
            coordinates: [-70.50704, -33.50194],
          },
        },
        {
          type: "Feature",
          properties: {
            countryCode: "CHL",
            countryName: "Chile",
            elevation: "16.0",
            organizationId: "124407",
            organizationName: "Escuela Rural de Niebla",
            protocol: "water_temperatures",
            siteId: "1494",
            siteName: "MUELLE NIEBLA:SWS-01",
            watertemperaturesComments: "null",
            watertemperaturesMeasuredAt: "2005-10-20T16:30:00",
            watertemperaturesTemperatureMethod: "null",
            watertemperaturesThermometerProbeMfg: "null",
            watertemperaturesThermometerProbeModel: "null",
            watertemperaturesUserid: "-1",
            watertemperaturesWaterBodyState: "normal",
            watertemperaturesWaterTempC: "12",
          },
          geometry: {
            type: "Point",
            coordinates: [-71.6, -33.95],
          },
        },
        {
          type: "Feature",
          properties: {
            countryCode: "CHL",
            countryName: "Chile",
            elevation: "1067.2",
            organizationId: "129720",
            organizationName: "Centro Educacional Valle Hermoso",
            protocol: "water_temperatures",
            siteId: "1487",
            siteName: "QUEBRADA DE MACUL  2:SWS-02",
            watertemperaturesComments:
              "PENSAMOS QUE EL LAPIZ PH UTILIZADO NO ES EL MAS INDICADO.",
            watertemperaturesMeasuredAt: "2005-10-15T12:51:00",
            watertemperaturesTemperatureMethod: "null",
            watertemperaturesThermometerProbeMfg: "null",
            watertemperaturesThermometerProbeModel: "null",
            watertemperaturesUserid: "-1",
            watertemperaturesWaterBodyState: "normal",
            watertemperaturesWaterTempC: "8",
          },
          geometry: {
            type: "Point",
            coordinates: [-70.50704, -33.50194],
          },
        },
        {
          type: "Feature",
          properties: {
            countryCode: "CHL",
            countryName: "Chile",
            elevation: "224.0",
            organizationId: "124407",
            organizationName: "Escuela Rural de Niebla",
            protocol: "water_temperatures",
            siteId: "1495",
            siteName: "ESTERO LA HUAIRONA:SWS-02",
            watertemperaturesComments: "null",
            watertemperaturesMeasuredAt: "2005-09-08T16:30:00",
            watertemperaturesTemperatureMethod: "null",
            watertemperaturesThermometerProbeMfg: "null",
            watertemperaturesThermometerProbeModel: "null",
            watertemperaturesUserid: "-1",
            watertemperaturesWaterBodyState: "normal",
            watertemperaturesWaterTempC: "12",
          },
          geometry: {
            type: "Point",
            coordinates: [-71.6, -33.95],
          },
        },
        {
          type: "Feature",
          properties: {
            countryCode: "CHL",
            countryName: "Chile",
            elevation: "16.0",
            organizationId: "124407",
            organizationName: "Escuela Rural de Niebla",
            protocol: "water_temperatures",
            siteId: "1494",
            siteName: "MUELLE NIEBLA:SWS-01",
            watertemperaturesComments:
              "NO SE MIDIO, EN LOS MESES ANTERIORES,POR LLUVIA.",
            watertemperaturesMeasuredAt: "2005-09-08T16:15:00",
            watertemperaturesTemperatureMethod: "null",
            watertemperaturesThermometerProbeMfg: "null",
            watertemperaturesThermometerProbeModel: "null",
            watertemperaturesUserid: "-1",
            watertemperaturesWaterBodyState: "normal",
            watertemperaturesWaterTempC: "12",
          },
          geometry: {
            type: "Point",
            coordinates: [-71.6, -33.95],
          },
        },
        {
          type: "Feature",
          properties: {
            countryCode: "CHL",
            countryName: "Chile",
            elevation: "224.0",
            organizationId: "124407",
            organizationName: "Escuela Rural de Niebla",
            protocol: "water_temperatures",
            siteId: "1495",
            siteName: "ESTERO LA HUAIRONA:SWS-02",
            watertemperaturesComments:
              "NO HAY MAS MEDICIONES POR FALTA DE INSTRUMENTOS",
            watertemperaturesMeasuredAt: "2005-05-04T16:15:00",
            watertemperaturesTemperatureMethod: "null",
            watertemperaturesThermometerProbeMfg: "null",
            watertemperaturesThermometerProbeModel: "null",
            watertemperaturesUserid: "-1",
            watertemperaturesWaterBodyState: "normal",
            watertemperaturesWaterTempC: "10.5",
          },
          geometry: {
            type: "Point",
            coordinates: [-71.6, -33.95],
          },
        },
        {
          type: "Feature",
          properties: {
            countryCode: "CHL",
            countryName: "Chile",
            elevation: "224.0",
            organizationId: "124407",
            organizationName: "Escuela Rural de Niebla",
            protocol: "water_temperatures",
            siteId: "1495",
            siteName: "ESTERO LA HUAIRONA:SWS-02",
            watertemperaturesComments: "null",
            watertemperaturesMeasuredAt: "2005-04-14T16:15:00",
            watertemperaturesTemperatureMethod: "null",
            watertemperaturesThermometerProbeMfg: "null",
            watertemperaturesThermometerProbeModel: "null",
            watertemperaturesUserid: "-1",
            watertemperaturesWaterBodyState: "normal",
            watertemperaturesWaterTempC: "11.5",
          },
          geometry: {
            type: "Point",
            coordinates: [-71.6, -33.95],
          },
        },
        {
          type: "Feature",
          properties: {
            countryCode: "CHL",
            countryName: "Chile",
            elevation: "1072.1",
            organizationId: "129720",
            organizationName: "Centro Educacional Valle Hermoso",
            protocol: "water_temperatures",
            siteId: "1486",
            siteName: "QUEBRADA DE MACUL:SWS-01",
            watertemperaturesComments:
              "FUE UN DIA AGRADABLE, POR PRIMERA VEZ SE REALIZARON TODOS LOS ANALISIS.",
            watertemperaturesMeasuredAt: "2003-08-07T19:00:00",
            watertemperaturesTemperatureMethod: "null",
            watertemperaturesThermometerProbeMfg: "null",
            watertemperaturesThermometerProbeModel: "null",
            watertemperaturesUserid: "-1",
            watertemperaturesWaterBodyState: "normal",
            watertemperaturesWaterTempC: "8.2",
          },
          geometry: {
            type: "Point",
            coordinates: [-70.5, -33.5],
          },
        },
        {
          type: "Feature",
          properties: {
            countryCode: "CHL",
            countryName: "Chile",
            elevation: "1072.1",
            organizationId: "129720",
            organizationName: "Centro Educacional Valle Hermoso",
            protocol: "water_temperatures",
            siteId: "1486",
            siteName: "QUEBRADA DE MACUL:SWS-01",
            watertemperaturesComments: "null",
            watertemperaturesMeasuredAt: "2003-03-09T13:30:00",
            watertemperaturesTemperatureMethod: "null",
            watertemperaturesThermometerProbeMfg: "null",
            watertemperaturesThermometerProbeModel: "null",
            watertemperaturesUserid: "-1",
            watertemperaturesWaterBodyState: "normal",
            watertemperaturesWaterTempC: "17",
          },
          geometry: {
            type: "Point",
            coordinates: [-70.5, -33.5],
          },
        },
        {
          type: "Feature",
          properties: {
            countryCode: "CHL",
            countryName: "Chile",
            elevation: "1072.1",
            organizationId: "129720",
            organizationName: "Centro Educacional Valle Hermoso",
            protocol: "water_temperatures",
            siteId: "1486",
            siteName: "QUEBRADA DE MACUL:SWS-01",
            watertemperaturesComments: "null",
            watertemperaturesMeasuredAt: "2003-03-02T13:30:00",
            watertemperaturesTemperatureMethod: "null",
            watertemperaturesThermometerProbeMfg: "null",
            watertemperaturesThermometerProbeModel: "null",
            watertemperaturesUserid: "-1",
            watertemperaturesWaterBodyState: "normal",
            watertemperaturesWaterTempC: "17",
          },
          geometry: {
            type: "Point",
            coordinates: [-70.5, -33.5],
          },
        },
        {
          type: "Feature",
          properties: {
            countryCode: "CHL",
            countryName: "Chile",
            elevation: "1072.1",
            organizationId: "129720",
            organizationName: "Centro Educacional Valle Hermoso",
            protocol: "water_temperatures",
            siteId: "1486",
            siteName: "QUEBRADA DE MACUL:SWS-01",
            watertemperaturesComments: "null",
            watertemperaturesMeasuredAt: "2003-02-22T13:30:00",
            watertemperaturesTemperatureMethod: "null",
            watertemperaturesThermometerProbeMfg: "null",
            watertemperaturesThermometerProbeModel: "null",
            watertemperaturesUserid: "-1",
            watertemperaturesWaterBodyState: "normal",
            watertemperaturesWaterTempC: "15.5",
          },
          geometry: {
            type: "Point",
            coordinates: [-70.5, -33.5],
          },
        },
        {
          type: "Feature",
          properties: {
            countryCode: "CHL",
            countryName: "Chile",
            elevation: "1072.1",
            organizationId: "129720",
            organizationName: "Centro Educacional Valle Hermoso",
            protocol: "water_temperatures",
            siteId: "1486",
            siteName: "QUEBRADA DE MACUL:SWS-01",
            watertemperaturesComments: "null",
            watertemperaturesMeasuredAt: "2003-02-08T13:30:00",
            watertemperaturesTemperatureMethod: "null",
            watertemperaturesThermometerProbeMfg: "null",
            watertemperaturesThermometerProbeModel: "null",
            watertemperaturesUserid: "-1",
            watertemperaturesWaterBodyState: "normal",
            watertemperaturesWaterTempC: "18",
          },
          geometry: {
            type: "Point",
            coordinates: [-70.5, -33.5],
          },
        },
        {
          type: "Feature",
          properties: {
            countryCode: "CHL",
            countryName: "Chile",
            elevation: "1072.1",
            organizationId: "129720",
            organizationName: "Centro Educacional Valle Hermoso",
            protocol: "water_temperatures",
            siteId: "1486",
            siteName: "QUEBRADA DE MACUL:SWS-01",
            watertemperaturesComments: "null",
            watertemperaturesMeasuredAt: "2003-02-01T17:05:00",
            watertemperaturesTemperatureMethod: "null",
            watertemperaturesThermometerProbeMfg: "null",
            watertemperaturesThermometerProbeModel: "null",
            watertemperaturesUserid: "-1",
            watertemperaturesWaterBodyState: "normal",
            watertemperaturesWaterTempC: "17",
          },
          geometry: {
            type: "Point",
            coordinates: [-70.5, -33.5],
          },
        },
        {
          type: "Feature",
          properties: {
            countryCode: "CHL",
            countryName: "Chile",
            elevation: "1072.1",
            organizationId: "129720",
            organizationName: "Centro Educacional Valle Hermoso",
            protocol: "water_temperatures",
            siteId: "1486",
            siteName: "QUEBRADA DE MACUL:SWS-01",
            watertemperaturesComments: "null",
            watertemperaturesMeasuredAt: "2003-01-25T17:05:00",
            watertemperaturesTemperatureMethod: "null",
            watertemperaturesThermometerProbeMfg: "null",
            watertemperaturesThermometerProbeModel: "null",
            watertemperaturesUserid: "-1",
            watertemperaturesWaterBodyState: "normal",
            watertemperaturesWaterTempC: "16",
          },
          geometry: {
            type: "Point",
            coordinates: [-70.5, -33.5],
          },
        },
        {
          type: "Feature",
          properties: {
            countryCode: "CHL",
            countryName: "Chile",
            elevation: "1072.1",
            organizationId: "129720",
            organizationName: "Centro Educacional Valle Hermoso",
            protocol: "water_temperatures",
            siteId: "1486",
            siteName: "QUEBRADA DE MACUL:SWS-01",
            watertemperaturesComments: "null",
            watertemperaturesMeasuredAt: "2003-01-18T17:05:00",
            watertemperaturesTemperatureMethod: "null",
            watertemperaturesThermometerProbeMfg: "null",
            watertemperaturesThermometerProbeModel: "null",
            watertemperaturesUserid: "-1",
            watertemperaturesWaterBodyState: "normal",
            watertemperaturesWaterTempC: "19.5",
          },
          geometry: {
            type: "Point",
            coordinates: [-70.5, -33.5],
          },
        },
        {
          type: "Feature",
          properties: {
            countryCode: "CHL",
            countryName: "Chile",
            elevation: "1072.1",
            organizationId: "129720",
            organizationName: "Centro Educacional Valle Hermoso",
            protocol: "water_temperatures",
            siteId: "1486",
            siteName: "QUEBRADA DE MACUL:SWS-01",
            watertemperaturesComments: "null",
            watertemperaturesMeasuredAt: "2003-01-11T17:05:00",
            watertemperaturesTemperatureMethod: "null",
            watertemperaturesThermometerProbeMfg: "null",
            watertemperaturesThermometerProbeModel: "null",
            watertemperaturesUserid: "-1",
            watertemperaturesWaterBodyState: "normal",
            watertemperaturesWaterTempC: "16",
          },
          geometry: {
            type: "Point",
            coordinates: [-70.5, -33.5],
          },
        },
        {
          type: "Feature",
          properties: {
            countryCode: "CHL",
            countryName: "Chile",
            elevation: "1072.1",
            organizationId: "129720",
            organizationName: "Centro Educacional Valle Hermoso",
            protocol: "water_temperatures",
            siteId: "1486",
            siteName: "QUEBRADA DE MACUL:SWS-01",
            watertemperaturesComments:
              "se encontro muy poco oxigeno disuelto para lo normal, se cree que la causa de esto es la temperatura del agua.",
            watertemperaturesMeasuredAt: "2002-12-20T15:30:00",
            watertemperaturesTemperatureMethod: "null",
            watertemperaturesThermometerProbeMfg: "null",
            watertemperaturesThermometerProbeModel: "null",
            watertemperaturesUserid: "-1",
            watertemperaturesWaterBodyState: "normal",
            watertemperaturesWaterTempC: "14",
          },
          geometry: {
            type: "Point",
            coordinates: [-70.5, -33.5],
          },
        },
        {
          type: "Feature",
          properties: {
            countryCode: "CHL",
            countryName: "Chile",
            elevation: "1072.1",
            organizationId: "129720",
            organizationName: "Centro Educacional Valle Hermoso",
            protocol: "water_temperatures",
            siteId: "1486",
            siteName: "QUEBRADA DE MACUL:SWS-01",
            watertemperaturesComments: "null",
            watertemperaturesMeasuredAt: "2002-12-14T15:50:00",
            watertemperaturesTemperatureMethod: "null",
            watertemperaturesThermometerProbeMfg: "null",
            watertemperaturesThermometerProbeModel: "null",
            watertemperaturesUserid: "-1",
            watertemperaturesWaterBodyState: "normal",
            watertemperaturesWaterTempC: "15",
          },
          geometry: {
            type: "Point",
            coordinates: [-70.5, -33.5],
          },
        },
        {
          type: "Feature",
          properties: {
            countryCode: "CHL",
            countryName: "Chile",
            elevation: "1072.1",
            organizationId: "129720",
            organizationName: "Centro Educacional Valle Hermoso",
            protocol: "water_temperatures",
            siteId: "1486",
            siteName: "QUEBRADA DE MACUL:SWS-01",
            watertemperaturesComments: "null",
            watertemperaturesMeasuredAt: "2002-12-07T16:45:00",
            watertemperaturesTemperatureMethod: "null",
            watertemperaturesThermometerProbeMfg: "null",
            watertemperaturesThermometerProbeModel: "null",
            watertemperaturesUserid: "-1",
            watertemperaturesWaterBodyState: "normal",
            watertemperaturesWaterTempC: "15",
          },
          geometry: {
            type: "Point",
            coordinates: [-70.5, -33.5],
          },
        },
        {
          type: "Feature",
          properties: {
            countryCode: "CHL",
            countryName: "Chile",
            elevation: "1072.1",
            organizationId: "129720",
            organizationName: "Centro Educacional Valle Hermoso",
            protocol: "water_temperatures",
            siteId: "1486",
            siteName: "QUEBRADA DE MACUL:SWS-01",
            watertemperaturesComments: "null",
            watertemperaturesMeasuredAt: "2002-11-30T16:55:00",
            watertemperaturesTemperatureMethod: "null",
            watertemperaturesThermometerProbeMfg: "null",
            watertemperaturesThermometerProbeModel: "null",
            watertemperaturesUserid: "-1",
            watertemperaturesWaterBodyState: "normal",
            watertemperaturesWaterTempC: "12",
          },
          geometry: {
            type: "Point",
            coordinates: [-70.5, -33.5],
          },
        },
        {
          type: "Feature",
          properties: {
            countryCode: "CHL",
            countryName: "Chile",
            elevation: "1072.1",
            organizationId: "129720",
            organizationName: "Centro Educacional Valle Hermoso",
            protocol: "water_temperatures",
            siteId: "1486",
            siteName: "QUEBRADA DE MACUL:SWS-01",
            watertemperaturesComments:
              "MUCHOS BA?ISTAS EN EL AGUA, SE NOS CAYO UNA ZAPATILLA AL AGUA Y TUVIMOS PROBLEMAS EN EL DESENSO.",
            watertemperaturesMeasuredAt: "2002-11-23T16:48:00",
            watertemperaturesTemperatureMethod: "null",
            watertemperaturesThermometerProbeMfg: "null",
            watertemperaturesThermometerProbeModel: "null",
            watertemperaturesUserid: "-1",
            watertemperaturesWaterBodyState: "normal",
            watertemperaturesWaterTempC: "17",
          },
          geometry: {
            type: "Point",
            coordinates: [-70.5, -33.5],
          },
        },
        {
          type: "Feature",
          properties: {
            countryCode: "CHL",
            countryName: "Chile",
            elevation: "1072.1",
            organizationId: "129720",
            organizationName: "Centro Educacional Valle Hermoso",
            protocol: "water_temperatures",
            siteId: "1486",
            siteName: "QUEBRADA DE MACUL:SWS-01",
            watertemperaturesComments:
              "se cree que hay menos oxigeno disuelto por la temperatura del agua,que es de 14 grados a diferencia de las semanas anteriores y por que se encontraron ba?istas un poco mas arriba de donde hacemos nuestros analisis.",
            watertemperaturesMeasuredAt: "2002-11-16T15:10:00",
            watertemperaturesTemperatureMethod: "null",
            watertemperaturesThermometerProbeMfg: "null",
            watertemperaturesThermometerProbeModel: "null",
            watertemperaturesUserid: "-1",
            watertemperaturesWaterBodyState: "normal",
            watertemperaturesWaterTempC: "14",
          },
          geometry: {
            type: "Point",
            coordinates: [-70.5, -33.5],
          },
        },
        {
          type: "Feature",
          properties: {
            countryCode: "CHL",
            countryName: "Chile",
            elevation: "1072.1",
            organizationId: "129720",
            organizationName: "Centro Educacional Valle Hermoso",
            protocol: "water_temperatures",
            siteId: "1486",
            siteName: "QUEBRADA DE MACUL:SWS-01",
            watertemperaturesComments: "null",
            watertemperaturesMeasuredAt: "2002-11-09T14:26:00",
            watertemperaturesTemperatureMethod: "null",
            watertemperaturesThermometerProbeMfg: "null",
            watertemperaturesThermometerProbeModel: "null",
            watertemperaturesUserid: "-1",
            watertemperaturesWaterBodyState: "normal",
            watertemperaturesWaterTempC: "10",
          },
          geometry: {
            type: "Point",
            coordinates: [-70.5, -33.5],
          },
        },
        {
          type: "Feature",
          properties: {
            countryCode: "CHL",
            countryName: "Chile",
            elevation: "1072.1",
            organizationId: "129720",
            organizationName: "Centro Educacional Valle Hermoso",
            protocol: "water_temperatures",
            siteId: "1486",
            siteName: "QUEBRADA DE MACUL:SWS-01",
            watertemperaturesComments: "null",
            watertemperaturesMeasuredAt: "2002-11-02T15:12:00",
            watertemperaturesTemperatureMethod: "null",
            watertemperaturesThermometerProbeMfg: "null",
            watertemperaturesThermometerProbeModel: "null",
            watertemperaturesUserid: "-1",
            watertemperaturesWaterBodyState: "normal",
            watertemperaturesWaterTempC: "10",
          },
          geometry: {
            type: "Point",
            coordinates: [-70.5, -33.5],
          },
        },
        {
          type: "Feature",
          properties: {
            countryCode: "CHL",
            countryName: "Chile",
            elevation: "1072.1",
            organizationId: "129720",
            organizationName: "Centro Educacional Valle Hermoso",
            protocol: "water_temperatures",
            siteId: "1486",
            siteName: "QUEBRADA DE MACUL:SWS-01",
            watertemperaturesComments: "null",
            watertemperaturesMeasuredAt: "2002-10-26T16:00:00",
            watertemperaturesTemperatureMethod: "null",
            watertemperaturesThermometerProbeMfg: "null",
            watertemperaturesThermometerProbeModel: "null",
            watertemperaturesUserid: "-1",
            watertemperaturesWaterBodyState: "normal",
            watertemperaturesWaterTempC: "10",
          },
          geometry: {
            type: "Point",
            coordinates: [-70.5, -33.5],
          },
        },
      ];

      const options: IChatCall = {
        model: {
          temperature: 0.5,
        },
        inputVariables: [
          {
            key: "data",
            value: JSON.stringify(data),
          },
        ],
        schema: exampleSchema,
        system: "Eres un experto en medioambiente, ecología y sostenibilidad.",
        prompt: `
          Dado los siguientes datos de la temperatura del agua en Chile:

          {data}
        `,
      };

      const response = await AI.callCompletion(options);
      console.log("response", response);
      return res.status(200).json(response);
    } catch (error: any) {
      console.error("error", error);
      return res.status(400).json(error.data);
    }
  }
);

export default handler;
